### PR TITLE
minor fixes to build on Mac OS

### PR DESCRIPTION
**Pull request by Yangqing**
This PR tries to make NCCL build on Mac - tested on Mac OS 10.12, clang 8.0.0 and cuda 8.0.

- I changed the Makefile to make sure that on Mac ("Darwin") we set the right lib and versions.
- It seems that clang 8.0.0 has an issue with nullptr_t so we need to manually specify the type.

I haven't tested this on a Linux box, but hopefully I haven't touched anything for Linux.

### CODE REVIEW

**Comment by Yangqing** [comment]
friendly ping @sjeaugey

**Comment by codeAC29** [comment]
Thank you @Yangqing !!! This fix was helpful.

**Comment by allenwq** [comment]
```
Compiling src/all_gather.cu                   > /Users/allen/Documents/dev/nccl/build/obj/all_gather.o
src/common_kernel.h(237): error: class "__half" has no member "x"

src/common_kernel.h(237): error: class "__half" has no member "x"

src/common_kernel.h(250): error: class "__half" has no member "x"

src/common_kernel.h(250): error: class "__half" has no member "x"

src/copy_kernel.h(28): error: class "__half" has no member "x"

src/copy_kernel.h(28): error: class "__half" has no member "x"

6 errors detected in the compilation of "/var/folders/yh/hys1jw_n29z1rkk87r9l4z8r0000gn/T//tmpxft_0001400c_00000000-8_all_gather.compute_52.cpp1.ii".
make: *** [/Users/allen/Documents/dev/nccl/build/obj/all_gather.o] Error 1```
get these errors on 10.12.6, CUDA 9.2

@Yangqing do you have any ideas?

**Comment by allenwq** [comment]
For those who are facing above issue, `git rebase master` will work.

**Comment by CapoeiraShaolin1** [comment]
(1) as comments allenwq on Jul1, 2018, I realize NVIDIA/NCCL/common_kernel.h has been revised for CUDA ver 9 or later. so, how about updating like this,


line 217 

#ifdef CUDA_HAS_HALF
#if CUDART_VERSION < 9000
template<> inline __device__
half vFetch<half>(const volatile half* ptr) {
  half r;
  r.x = ptr->x;
  return r;
}
#else
template<> inline __device__
half vFetch<half>(const volatile half* ptr) {
  half r;
  r = ((half*)ptr)[0];
  return r;
}

#endif /* CUDART_VERSION */
#endif /* CUDA_HAS_HALF */

template<typename T> inline __device__
void vStore(volatile T* ptr, const T val) {
  *ptr = val;
}
#ifdef CUDA_HAS_HALF
#if CUDART_VERSION < 9000
template<> inline __device__
void vStore<half>(volatile half* ptr, const half val) {
  ptr->x = val.x;
}
#else
template<> inline __device__
void vStore<half>(volatile half* ptr, const half val) {
  ((half*)ptr)[0] = val;
}
#endif /* CUDART_VERSION */
#endif /* CUDA_HAS_HALF */


(2) ncclAllGather() arguments looks conflicts of position of recvbuff against NVIDIA/NCCL/nccl.h. so could you check nccl.h and all_gather.cu. it should be 

ncclResult_t  ncclAllGather(const void* sendbuff, void* recvbuff, int count,
    ncclDataType_t datatype, ncclComm_t comm, cudaStream_t stream);
ncclResult_t pncclAllGather(const void* sendbuff, void* recvbuff, int count,
    ncclDataType_t datatype, ncclComm_t comm, cudaStream_t stream);

Thanks,

**Comment by CapoeiraShaolin1** [comment]
libwrap.cu loads "libnvidia-ml.so" (memory management) but which is Not available for MacOS. does anyone find solution to resolve missing libnvidia-ml.so for MacOS?
