### ISSUE TITLE
`thrust::partition` failed to compile on CUDA 12.2

### ISSUE THREAD

**Issue by condy0919** [NVIDIA/nccl#1204]
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Jun_13_19:16:58_PDT_2023
Cuda compilation tools, release 12.2, V12.2.91
Build cuda_12.2.r12.2/compiler.32965470_0
```

The following example

```cuda
#include <cuda_runtime_api.h>
#include <thrust/device_vector.h>
#include <thrust/execution_policy.h>
#include <thrust/partition.h>

__global__ void foo(int arr[], int n) {
  thrust::partition(thrust::device, arr, arr + n,
                    [](int x) { return x % 2 == 1; });
}

int main(int argc, char *argv[]) {
  thrust::device_vector<int> vec;
  for (int i = 0; i < 10; ++i) {
    vec.push_back(i);
  }

  foo<<<1, 1>>>(vec.data().get(), vec.size());

  cudaDeviceSynchronize();

  return 0;
}
```

failed to compile and nvcc reported an odd error.

```text
In file included from tmpxft_00228c92_00000000-6_a.cudafe1.stub.c:1:
/tmp/tmpxft_00228c92_00000000-6_a.cudafe1.stub.c:10:195: error: template argument 5 is invalid
   10 | b::__partition::PartitionAgent<int *,  ::thrust::cuda_cub::__partition::no_stencil_tag_ *, int *, ::thrust::cuda_cub::__partition::single_output_tag_ *,  ::, long, long *> ::ScanTil
eState _ZN6thrust8cuda_cub11__partition14PartitionAgentIPiPNS1_15no_stencil_tag_ES3_PNS1_18single_output_tag_EZ3fooS3_iEUliE_lPlE13ScanTileStateE;
      |                                                                                                                                                                            ^

/tmp/tmpxft_00228c92_00000000-6_a.cudafe1.stub.c:10:213: error: expected initializer before ‘_ZN6thrust8cuda_cub11__partition14PartitionAgentIPiPNS1_15no_stencil_tag_ES3_PNS1_18single_output
_tag_EZ3fooS3_iEUliE_lPlE13ScanTileStateE’
   10 | rtitionAgent<int *,  ::thrust::cuda_cub::__partition::no_stencil_tag_ *, int *,  ::thrust::cuda_cub::__partition::single_output_tag_ *,  ::, long, long *> ::ScanTileState _ZN6thrust8
cuda_cub11__partition14PartitionAgentIPiPNS1_15no_stencil_tag_ES3_PNS1_18single_output_tag_EZ3fooS3_iEUliE_lPlE13ScanTileStateE;
      |                                                                                                                                                                            ^~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

where the 5th template argument is `::`.

**Comment by condy0919** [comment]
Oh, I should post it on https://github.com/nvidia/cccl repo. closed.
